### ISSUE TITLE
Gas optimisation for Loops

### ISSUE THREAD

**Issue by FrankNFT-labs** [LightArtists/light-smart-contracts#2]
There are a lot of for() loops in this contract and those will eat a lot of gas.

Instead of doing this:

        for (uint256 mintCounter = 0; mintCounter < quantity; mintCounter++) {
            _mint(msg.sender, _assembleTokenID(dropID, drop.quantitySold));
            drop.quantitySold++;
        }
        
Do this:

        for (uint256 mintCounter = 0; mintCounter < quantity; ) {
            _mint(msg.sender, _assembleTokenID(dropID, drop.quantitySold));
            unchecked{
                drop.quantitySold++;
                mintCounter++
            }
        }       
        
This will shave of some gas on each iteration.
P.S. also works on while loops!

**Comment by fulldecent** [comment]
Thank you for sharing!

We use loops in several places, here they are:

- `freezeMetadataForDrop`
- `_getEffectivePhase`
- `setDropPhases`
- `mintRandom`
- `mintChosen`

I agree that unchecked math, and your specific suggestions, should reduce gas usage. Gas improvements are included in this bug bounty, but there must be some threshold, perhaps 5% or 10% improvement. Or possibly less if this is an especially expensive operation, like Area NFT's expensive minting, splitting and marketplace functions. Of course, saving an unneeded storage variable will almost always hit this threshold.

In the lifecycle of a token, it will at least be minted and metadata frozen. This is a minimum of one `SSTORE`, 20000 gas. So a worthwhile optimization should be maybe 2000 or 1000 gas (some `SLOAD`s). This optimization is a few arithmetic operations, which is 10s of gas. As such it is not worth the complexity of adding an extra line of code. Over the course of selling 200 tokens in the first drop, these optimizations may perhaps only save USD 1 cumulatively across all the transactions. (Just checked, wow gas and Ether are cheap right now.)

I do not recommend this issue to be eligible for the bounty.

BUT I do think your advice could be built into Solidity itself. Multiplied by every transaction, on every contract, and every function, this might be worthwhile. I have started the discussion on that topic here, with credit to you.

https://github.com/ethereum/solidity/issues/13308

**Comment by fulldecent** [comment]
We reviewed this one further and did not take this optimization. It seems this is relatively minor. But upstream in the Solidity project, this is well received and over there we are discussing how to implement this.

Thank you!
