### ISSUE TITLE
If a user gives more eth then what it costs then  there is leakage of value,extra users funds wont be given back

### ISSUE THREAD

**Issue by snn20** [LightArtists/light-smart-contracts#4]
## Details
 Light.sol
```
  function mintRandom(
        uint64 dropID,
        uint64 quantity,
        bytes32[] calldata accessListProof,
        uint96 accessListQuantity
    ) external payable {
        Drop storage drop = drops[dropID];
        require(quantity > 0, "Light: missing purchase quantity");
        require(quantity + drop.quantitySold <= drop.quantityForSale, "Light: not enough left for sale");
        require(drop.accumulatedRandomness != 0, "Light: no randomness in this drop, use mintChosen instead");

        DropPhase memory dropPhase = _getEffectivePhase(drop);
        require(msg.value >= dropPhase.ethPrice * quantity, "Light: not enough Ether paid");
        }
    }
```
and 
```
   DropPhase memory dropPhase = _getEffectivePhase(drop);
        require(msg.value >= dropPhase.ethPrice * tokenIDsInDrop.length, "Light: not enough Ether paid");

        if (dropPhase.accessListRoot != bytes32(0)) {
            _requireValidMerkleProof(dropPhase.accessListRoot, accessListProof, accessListQuantity);
            require(
                quantityMinted[dropPhase.accessListRoot][msg.sender] + tokenIDsInDrop.length <= accessListQuantity,
                "Light: exceeded access list limit"
            );
        }


```
If user pays  more eth then required then   the user's eth will be stuck in the contract and the user  looses those extra funds.
There are a few scenarios that is can happen if the user expects the price to go up when the user is making the tx   or  if  there is 
 reverse dutch action functionallity that  when a user makes tx thinking the price is 1 eth but  in the same block  and with  a better gas fee a seller underbids which is common(in reserve dutch auctions)    with price of 0.9 eth so the user 0.1 eth is lost in the contract and there is no way of getting the user's refund.
Also it can just be user mistake but it still matters if  you care about your users.
## Recommend Mitagations
 1. have instead of `require(msg.value >= price* quantity);`
There are few ways of fixing this the first way is to be restricitive on the amount a user pays 
have `require(msg.value == price*quantity);`
2. This way is more gas consuming but works
`require(msg.value >= price* quantity);`
have mappings that is has address to how much eth they gave over
`mapping (address => uint)leftover;`
ex:
```
if(msg.value > price* quantity){
leftover[msg.sender]=msg.value - price*quantity;
}
else if (msg.vlaue  == quanity){
do ...
}
else {
revert("not enough");
}
```
then  you can have a  owner function  that gives out the funds or function that gives msg.sender there leftover funds back.
```
function giveback() external  {
uint leftover=leftover[msg.sender];
if(leftover >0);
(bool success, )=msg.sender.call{value : leftover}("");
require(success,"give back failed");
```
3. just do the call in the function but add reentracy gaurd if effects arent done yet when this call is happening. 
```
if (msg.value > price * quantity){
uint amount =  msg.value - price * quantity;
msg.sender.call{value : amount}("");
}
else if ( msg.value == price * quantity){
do...
}
else {
revert("not enough funds");
}

```
then conintue with the function but then you have to worry about **reentry** so if you use this method use nonReentracy gaurd or lock modifer.
You can which  every one you want but each fix has   some sort of drawback.
Also  if  you choose to not fix it then just put a warning as comment and on the website.
## References
https://en.wikipedia.org/wiki/Reverse_auction
https://github.com/LightArtists/light-smart-contracts/blob/a1de85cdadedc11af142cff30c96d1beeb7d280f/contracts/Light.sol#L185
https://github.com/LightArtists/light-smart-contracts/blob/a1de85cdadedc11af142cff30c96d1beeb7d280f/contracts/Light.sol#L143

**Comment by fulldecent** [comment]
This was intentional. If the customer is paying too much Ether, this would be their mistake.

It is possible for us to accumulate these and send it back, but this adds complexity and cost to transactions.

We can review this implementation and see if adding this makes sense.
